name: abstarct_date
description: Abstract date is a fluent abstract date system for working with different date types.
version: 0.0.5+3
homepage: https://github.com/ali2236/abstarct_date
author: Aligator <aligator2236@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  libcalendar: ^0.2.0
  hijri: ^0.2.5
#  path: ^1.6.0

dev_dependencies:
  #pedantic: ^1.8.0
  test: ^1.6.0
