name: abstarct_date
description: A starting point for Dart libraries or applications.
version: 0.0.2
homepage: https://github.com/ali2236/abstarct_date
author: Aligator <aligator2236@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
